{
    "fever": "fever",
    "cough": "cough",
    "runny_nose": "runny nose",
    "sore_throat": "sore throat",
    "fatigue": "fatigue",
    "body_aches": "body aches",
    "rash": "rash",
    "itchiness": "itchiness",
    "swollen_glands": "swollen glands",
    "vomiting": "vomiting",
    "diarrhea": "diarrhea",
    "abdominal_pain": "abdominal pain",
    "wheezing": "wheezing",
    "difficulty_breathing": "difficulty breathing",
    "ear_pain": "ear pain",
    "difficulty_sleeping": "difficulty sleeping",
    "sneezing": "itchy eyes",
    "itchy_eyes": "itchy eyes",
    "high_fever": "high fever",
    "blisters": "blisters",
    "excessive_thirst": "excessive thirst",
    "frequent_urination": "frequent urination",
    "unexplained_weight_loss": "unexplained weight loss",
    "facial_pain": "facial pain",
    "headache": "headache",
    "nasal_congestion": "nasal congestion",
    "dehydration": "dehydration",
}