symptoms = {
    "fever": True,
    "cough": True,
    "runny_nose": True,
    "sore_throat": True,
    "fatigue": True,
    "body_aches": True,
    "rash": True,
    "itchiness": True,
    "swollen_glands": True,
    "vomiting": True,
    "diarrhea": True,
    "abdominal_pain": True,
    "wheezing": True,
    "difficulty_breathing": True,
    "ear_pain": True,
    "difficulty_sleeping": True,
    "sneezing": True,
    "itchy_eyes": True,
    "high_fever": True,
    "blisters": True,
    "excessive_thirst": True,
    "frequent_urination": True,
    "unexplained_weight_loss": True,
    "facial_pain": True,
    "headache": True,
    "nasal_congestion": True,
    "dehydration": True
}

symptoms = [
    "fever",
    "cough",
    "runny_nose",
    "sore_throat",
    "fatigue",
    "body_aches",
    "rash",
    "itchiness",
    "swollen_glands",
    "vomiting",
    "diarrhea",
    "abdominal_pain",
    "wheezing",
    "difficulty_breathing",
    "ear_pain",
    "difficulty_sleeping",
    "sneezing",
    "itchy_eyes",
    "high_fever",
    "blisters",
    "excessive_thirst",
    "frequent_urination",
    "unexplained_weight_loss",
    "facial_pain",
    "headache",
    "nasal_congestion",
    "dehydration"
]